FROM node:12.21.0-alpine3.12
RUN apk add --no-cache make pkgconfig gcc g++ python3 libx11-dev libxkbfile-dev
WORKDIR /home/theia
COPY /.npmmegarc /root/.npmrc
ADD next.json ./package.json
ARG GITHUB_TOKEN
RUN yarn config set registry http://host.docker.internal:4873 && \
    yarn --pure-lockfile && \
    NODE_OPTIONS="--max_old_space_size=4096" yarn theia build && \
    yarn theia download:plugins && \
    yarn --production && \
    yarn autoclean --init && \
    echo *.ts >> .yarnclean && \
    echo *.ts.map >> .yarnclean && \
    echo *.spec.* >> .yarnclean && \
    yarn autoclean --force && \
    yarn cache clean

FROM node:12.21.0-alpine3.12
RUN addgroup theia && \
    adduser -G theia -s /bin/sh -D theia;
RUN chmod g+rw /home && \
    mkdir -p /home/project && \
    chown -R theia:theia /home/theia && \
    chown -R theia:theia /home/project;
RUN apk add --no-cache git openssh bash
ENV HOME /home/theia
WORKDIR /home/theia
COPY --from=0 --chown=theia:theia /home/theia /home/theia
# COPY --chown=theia:theia /packages/callhierarchy/. /home/project/.
WORKDIR /home/project
RUN git clone https://github.com/fastify/fastify.git
RUN chown -R theia:theia /home/project && chmod -R g+rw /home/project
WORKDIR /home/theia
EXPOSE 3000
ENV SHELL=/bin/bash \
    THEIA_DEFAULT_PLUGINS=local-dir:/home/theia/plugins
USER theia
ENTRYPOINT [ "node", "/home/theia/src-gen/backend/main.js", "/home/project/fastify", "--hostname=0.0.0.0" ]
